#!/bin/bash

echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &> /dev/null
echo $DOCKER_USERNAME
echo $DOCKER_PASSWORD
#TAG="${TARGET_VERSION:-latest}"
docker buildx build \
    --platform=linux/amd64,linux/arm64 \
    -t kevin0205/metricbeat:7.5.2 \
    -t kevin0205/metricbeat \
    --load \
    .
docker tag kevin0205 kevin0205/metricbeat
docker push kevin0205/metricbeat
