#!/bin/bash

apt-get update
apt-get install wget sudo
wget https://github.com/balena-io/qemu/releases/download/v4.0.0%2Bbalena2/qemu-4.0.0.balena2-arm.tar.gz | tar zxvf - -C . && mv qemu-4.0.0+balena2-arm/qemu-arm-static .
