#!/bin/bash
# downloads a local copy of qemu on docker-hub build machines
curl -L https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz | tar zxvf - -C . && mv qemu-3.0.0+resin-arm/qemu-arm-static .

mkdir -p $HOME/.docker/cli-plugins
wget -O $HOME/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
chmod 0750 $HOME/.docker/cli-plugins/docker-buildx
#echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json

# Check Version
lsb_release -a
uname -r
docker version
docker buildx version
ls -al /proc/sys/fs/binfmt_misc/
docker buildx inspect xbuilder --bootstrap
docker buildx ls
